-- CreateTable
CREATE TABLE `lead_forms` (
    `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    `agent_name` VARCHAR(255) NULL,
    `agent_id` VARCHAR(100) NULL,
    `sale_date` DATE NULL,
    `closer_name` VARCHAR(255) NULL,
    `cust_title` VARCHAR(255) NULL,
    `cust_first_name` VARCHAR(255) NULL,
    `cust_middle_name` VARCHAR(255) NULL,
    `cust_last_name` VARCHAR(255) NULL,
    `address` VARCHAR(255) NULL,
    `pincode` VARCHAR(255) NULL,
    `city` VARCHAR(255) NULL,
    `country` VARCHAR(255) NULL,
    `phone` VARCHAR(255) NULL,
    `password` VARCHAR(255) NULL,
    `dob` DATE NULL,
    `process` VARCHAR(255) NULL,
    `plan` VARCHAR(255) NULL,
    `plan_fee` VARCHAR(255) NULL,
    `name_of_bank` VARCHAR(255) NULL,
    `account_name` VARCHAR(255) NULL,
    `account_number` VARCHAR(255) NULL,
    `sort_code` VARCHAR(255) NULL,
    `appliance` VARCHAR(255) NULL,
    `make_of_appliance` VARCHAR(255) NULL,
    `age` VARCHAR(255) NULL,
    `card_number` VARCHAR(255) NULL,
    `cardType` VARCHAR(100) NULL,
    `expMonth` VARCHAR(100) NULL,
    `expYear` INTEGER NULL,
    `card_cvv_number` VARCHAR(255) NULL,
    `comment` TEXT NULL,
    `product_details` TEXT NULL,
    `deleted_at` TIMESTAMP(0) NULL,
    `created_at` TIMESTAMP(0) NULL,
    `updated_at` TIMESTAMP(0) NULL,

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
